environment:
  - SECRET_KEY
  - DEBUG=False
  - ALLOWED_HOSTS=*

resources:
  database:
    type: postgres
    options:
      storage: 10
      version: 13

services:
  web:
    build: .
    command: gunicorn mysite.wsgi --bind=0.0.0.0:8000 --workers=2
    port: 8000
    health: /admin/login/
    scale:
      count: 10
      cpu: 4000
      memory: 4096
    resources:
      - database
    
  migrate:
    build: .
    command: python manage.py migrate
    scale:
      count: 0  # Template service for migrations
    resources:
      - database
